# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caninos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocanino',
            name='detalle_registro',
            field=models.CharField(max_length=200),
        ),
    ]
