# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caninos', '0003_auto_20170529_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocaninodocumento',
            name='nombre_documento',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
